export const GALLERY = [
    {
        title: "Kundli Analysis",
        desc: "Get a detailed analysis of your birth chart to understand your personality, career, relationships, and future opportunities.",
        image: "/images/blog1.svg",
        category: "Astrology Services",
        author: "Pandit Rajesh Sharma",
        authorRole: "Vedic Astrologer",
        authorCompany: "Vedic Astrology",
        authorCompanyUrl: "#",
        authorImage: "/images/person-one.jpg",
    },
    {
        title: "Marriage Compatibility",
        desc: "Discover relationship compatibility through traditional Kundli matching and planetary analysis.",
        image: "/images/blog2.svg",
        category: "Marriage Astrology",
        author: "Pandit Rajesh Sharma",
        authorRole: "Marriage Consultant",
        authorCompany: "Vedic Astrology",
        authorCompanyUrl: "#",
        authorImage: "/images/person-three.jpg",
    },
    {
        title: "Puja & Spiritual Remedies",
        desc: "Perform personalized rituals, mantras, and remedies based on your horoscope and planetary positions.",
        image: "/images/blog3.svg",
        category: "Spiritual Services",
        author: "Pandit Rajesh Sharma",
        authorRole: "Vedic Priest",
        authorCompany: "Sanatan Services",
        authorCompanyUrl: "#",
        authorImage: "/images/person-four.jpg",
    },
    {
        title: "Career & Life Guidance",
        desc: "Receive astrology-based guidance to make informed decisions about career, finance, and personal growth.",
        image: "/images/blog1.svg",
        category: "Astrology Consultation",
        author: "Pandit Rajesh Sharma",
        authorRole: "Astrology Expert",
        authorCompany: "Vedic Astrology",
        authorCompanyUrl: "#",
        authorImage: "/images/person-five.jpg",
    },
];